### ISSUE TITLE
User-owned CA for AWS IoT guide is misleading

### ISSUE THREAD

**Issue by boraozgen** [Infineon/personalize-optiga-trust#1]
Hello,

We are testing the Optiga Trust X and AWS IoT integration. The AWS Root CA method is very well written and it works. However the user-owned CA guide lacks some critical information.

First, step 4 is completely wrong and the step probably belongs to the AWS Root CA guide.

Furthermore, it does not mention any of the additional steps described in the [AWS documentation](https://docs.aws.amazon.com/iot/latest/developerguide/auto-register-device-cert.html), such as the requirement of sending the CA certificate together with the client certificate, or the requirement of external activation of the pending certificate.

Otherwise the detailed guides and resources are much appreciated!

**Comment by ayushev** [comment]
hi @boraozgen 

I've tried to address your points here. Please let me know whether it helps or if you have a direct question on how to proceed dont hesistate to ask.
Commit https://github.com/Infineon/personalize-optiga-trust/commit/e5749d606603928d0281c5e270de191406695666

**Comment by boraozgen** [comment]
Thanks for the quick response. 4th step makes more sense now since the certificate is registered manually. Still, when we tried to follow the steps yesterday, the following line failed due to the missing file:

```
#Extract the ARN
$ export AWS_ARN=$(sed 's/.//;s/.$//' optiga.aws_arn)
```

**Comment by ayushev** [comment]
You are welcome and absolutly right!
Here is the fix
https://github.com/Infineon/personalize-optiga-trust/commit/019bab51cd55b249b467e230ce9f79e2c2930db5

**Comment by boraozgen** [comment]
Great, soon I will go through the steps again and report if anything is missing. Closing this one.
